import { StyleSheet, Font } from '@react-pdf/renderer';

// Register fonts
Font.register({
    family: 'Pretendard',
    fonts: [
        { src: '/fonts/Pretendard-Regular.ttf' },
        { src: '/fonts/Pretendard-Bold.ttf', fontWeight: 'bold' },
        { src: '/fonts/Pretendard-SemiBold.ttf', fontWeight: 600 },
    ],
});

export const movieStyles = StyleSheet.create({
    container: {
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        position: 'relative',
        backgroundColor: 'white',
        fontFamily: 'Pretendard',
    },
    titleSection: {
        position: 'absolute',
        left: 0,
        top: '50%',
        width: '30%',
        height: '50%',
        backgroundColor: '#00B15C',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    title: {
        color: 'white',
        fontSize: 24,
        fontFamily: 'Pretendard',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    mainImageSection: {
        width: '100%',
        height: '50%',
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    mainImage: {
        width: '100%',
        height: '100%',
        objectFit: 'contain',
    },
    directorSection: {
        position: 'absolute',
        right: 0,
        top: '50%',
        width: '70%',
        height: '50%',
        padding: 40,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
    },
    directorTitle: {
        fontSize: 18,
        fontFamily: 'Pretendard',
        fontWeight: 'bold',
        marginBottom: 12,
        color: '#333333',
    },
    directorContent: {
        fontSize: 12,
        fontFamily: 'Pretendard',
        lineHeight: 1.6,
        color: '#666666',
    },
    secondarySection: {
        flex: 1,
        padding: 40,
        display: 'flex',
        flexDirection: 'column',
        gap: 24,
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 16,
        color: '#333333',
    },
    sectionContent: {
        fontSize: 16,
        lineHeight: 1.6,
        color: '#666666',
    },
    // 두 번째 페이지 스타일
    secondPageContainer: {
        padding: '40px 30px',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
        height: '100%',
        position: 'relative',
        fontFamily: 'Pretendard',
    },
    contentWrapper: {
        display: 'flex',
        flexDirection: 'column',
        gap: 30,
        marginBottom: 30,
    },
    contentSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: 12,
    },
    contentTitle: {
        fontSize: 16,
        fontFamily: 'Pretendard',
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#333333',
    },
    contentText: {
        fontSize: 11,
        fontFamily: 'Pretendard',
        lineHeight: 1.6,
        color: '#666666',
        textAlign: 'justify',
    },
    secondImageSection: {
        width: '100%',
        height: '200px',
        marginTop: 'auto',
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    secondImage: {
        maxWidth: '80%',
        maxHeight: '180px',
        objectFit: 'contain',
    },
    pageNumber: {
        position: 'absolute',
        bottom: 30,
        right: 30,
        fontSize: 10,
        fontFamily: 'Pretendard',
        color: '#666666',
    },
});
